name: Molecule
'on':
  - push
  - pull_request
jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: |
          python -m pip install --disable-pip-version-check editorconfig-checker flake8 pytest testinfra
          python -m pip install --disable-pip-version-check ansible ansible-lint molecule yamllint molecule-plugins[docker]

      - name: Run Molecule tests
        run: |
          make version
          make test
